# Generated by Django 5.1.3 on 2025-02-09 10:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ownerdetails',
            name='user',
        ),
        migrations.RemoveField(
            model_name='userdetails',
            name='user',
        ),
    ]
