# Generated by Django 5.1.3 on 2025-02-18 05:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0002_remove_ownerdetails_user_remove_userdetails_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salon',
            name='image_name',
        ),
        migrations.RemoveField(
            model_name='service',
            name='image_name',
        ),
        migrations.AddField(
            model_name='salon',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='salons/'),
        ),
        migrations.AddField(
            model_name='service',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='services', to='myApp.category'),
        ),
        migrations.AddField(
            model_name='service',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='services/'),
        ),
    ]
