# Generated by Django 5.1.3 on 2025-02-08 06:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0003_example'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Example',
        ),
    ]
