# Generated by Django 5.1.3 on 2025-02-28 06:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0003_remove_salon_image_name_remove_service_image_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userdetails',
            name='last_login',
        ),
    ]
