# Generated by Django 5.1.3 on 2025-02-28 06:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0004_remove_userdetails_last_login'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userdetails',
            name='date_joined',
        ),
        migrations.RemoveField(
            model_name='userdetails',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='userdetails',
            name='is_staff',
        ),
        migrations.RemoveField(
            model_name='userdetails',
            name='is_superuser',
        ),
    ]
