# Generated by Django 5.1.3 on 2025-02-28 06:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0005_remove_userdetails_date_joined_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ownerdetails',
            name='date_joined',
        ),
        migrations.RemoveField(
            model_name='ownerdetails',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='ownerdetails',
            name='is_staff',
        ),
        migrations.RemoveField(
            model_name='ownerdetails',
            name='is_superuser',
        ),
        migrations.RemoveField(
            model_name='ownerdetails',
            name='last_login',
        ),
    ]
